### PR TITLE
update golangci-lint

### PR DESCRIPTION
**Pull request by cbartoszDell**
Update of golangci-lint and go version used in linters actions.

### CODE REVIEW

**Review by shaynafinocchiaro — DISMISSED** [review]

**Review by atye — APPROVED** [review]

**Review by alikdell — APPROVED** [review]

**Review by shaynafinocchiaro — APPROVED** [review]

**Review by xuluna — APPROVED** [review]

**Comment by xuluna** [comment]
Should the PR fix linting errors before getting merged?

**Comment by cbartoszDell** [comment]
> Should the PR fix linting errors before getting merged?

This PR is just for updating the version of golangci-lint, not for fixing the issues.

**Review by donatwork — DISMISSED** [review]

**Comment by shaynafinocchiaro** [comment]
@cbartoszDell Linting issues were addressed in an earlier PR #185. This is a regression.

**Comment by alikdell** [comment]
> > Should the PR fix linting errors before getting merged?
> 
> This PR is just for updating the version of golangci-lint, not for fixing the issues.

If we are not fixing linting error, what is the point of version upgrade?

**Comment by cbartoszDell** [comment]
This PR is only for upgrading the versions on Go and golangci-lint action. @alikdell This is required to make sure that golangci-lint is always the latest version and is working with the latest version of Go. This requests is being made to all CSM drivers and modules to make sure linter action keeps working. Fixing linter warnings is not a part of scope of this upgrade PR.

**Comment by alikdell** [comment]
> This PR is only for upgrading the versions on Go and golangci-lint action. @alikdell This is required to make sure that golangci-lint is always the latest version and is working with the latest version of Go. This requests is being made to all CSM drivers and modules to make sure linter action keeps working. Fixing linter warnings is not a part of scope of this upgrade PR.

The lintings errors were fixed. Now any PR goes that must fix any remaining linting error. Scope or not scope do not come up. You have linting error, fix it.

image

**Review by alikdell — DISMISSED** [review]
Linting errors must be fixed, irrespective of scope of work. We recently fixed all linting errors in this repo, we will not allow any PR with linting errors to merge

**Comment by jooseppi-luna** [comment]
Yes I second Alik and others, the linting errors were fixed last week, we should not allow them to regress.

**Review by alikdell — APPROVED** [review]

**Review by xuluna — APPROVED** [review]

**Pull request merged**
